#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TEMPLATE: build_sections.py — generated by new_book.py.
注入项: SECTIONS / NOTES_SUBHEADS"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
items = json.load(open(os.path.join(HERE, 'stream_raw.json'), encoding='utf-8'))

SECTIONS = __SECTIONS__
NOTES_SUBHEADS = __NOTES_SUBHEADS__

def norm(s):
    return ' '.join(s.split())

def is_noise(t):
    t = t.strip()
    if not t:
        return True
    if re.fullmatch(r'[\d\s\.\-\[\]ivxlcdmIVXLCDM]+', t):
        return True
    return False

def first_on_page(pg):
    for x in items:
        if x['page'] == pg and x['type'] in ('text', 'ref_text'):
            t = norm(x['text']).strip()
            if not is_noise(t) and t != 'This page intentionally left blank':
                return t
    return None

def main():
    results = []
    for sid, title, (a, b), is_notes in SECTIONS:
        paras = []
        if is_notes:
            pending = None
            def flush():
                nonlocal pending
                if pending:
                    paras.append({"type": 'note', "text": pending})
                pending = None
            for x in items:
                if x['page'] < a or x['page'] > b:
                    continue
                t = norm(x['text']).strip()
                if is_noise(t) or t == 'This page intentionally left blank':
                    continue
                if t in NOTES_SUBHEADS:
                    flush(); paras.append({"type": 'subh', "text": t}); continue
                if re.match(r'^\d+\.\s', t) or re.match(r'^[a-z]\.\s', t):
                    flush(); pending = t
                else:
                    pending = t if pending is None else pending + ' ' + t
            flush()
        else:
            ht = first_on_page(a)
            if ht:
                paras.append({"type": 'h', "text": ht})
            for x in items:
                if x['page'] < a or x['page'] > b:
                    continue
                t = norm(x['text']).strip()
                if is_noise(t) or t == 'This page intentionally left blank':
                    continue
                if t == ht:
                    continue
                paras.append({"type": 'text', "text": t})
        dedup = []
        for p in paras:
            if dedup and dedup[-1]['text'] == p['text'] and dedup[-1]['type'] == p['type']:
                continue
            dedup.append(p)
        results.append({"id": sid, "title": title, "paras": dedup})
        print(f"{sid:12s} paras={len(dedup):4d} chars={sum(len(p['text']) for p in dedup):7d} | {(dedup[0]['text'][:40] if dedup else '')}", flush=True)
    with open(os.path.join(HERE, 'en_data.json'), 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False)
    print(f"\nTOTAL sections={len(results)} paras={sum(len(s['paras']) for s in results)}", flush=True)

if __name__ == '__main__':
    main()