# -*- coding: utf-8 -*-
"""TEMPLATE: slots.py — generated by new_book.py.
注入项: TOC_ORDER / TOC_LABEL_BODY / TITLE_MAP_BODY / SECTITLE_BODY
"""

TOC_ORDER = __TOC_ORDER__

TOC_LABEL_BODY = __TOC_LABEL__

TITLE_MAP_BODY = __TITLE_MAP__

SECTITLE_BODY = __SECTITLE__