# -*- coding: utf-8 -*-
"""TEMPLATE: slots.py — generated by new_book.py.
注入项: TOC_ORDER / TOC_LABEL_BODY / TITLE_MAP_BODY / SECTITLE_BODY
"""

TOC_ORDER = ['ack', 'overture', 'ch1', 'ch2', 'ch3', 'ch4', 'ch5', 'ch6', 'finale', 'notes']

TOC_LABEL_BODY = {
    "ack": [
        "Acknowledgments",
        "致谢"
    ],
    "overture": [
        "Overture",
        "序曲"
    ],
    "ch1": [
        "Ch.1 · Looking Back at Opera in Late Imperial China",
        "第一章 · 回望帝制晚期的戏曲"
    ],
    "ch2": [
        "Ch.2 · Changing Discourses on China's Drama",
        "第二章 · 中国戏剧话语的变迁"
    ],
    "ch3": [
        "Ch.3 · The Reformation of Beijing Opera in Shanghai",
        "第三章 · 上海京剧的改良"
    ],
    "ch4": [
        "Ch.4 · Reformed Opera on the Shanghai Stage",
        "第四章 · 上海舞台上的改良戏曲"
    ],
    "ch5": [
        "Ch.5 · Reformed Opera in Xi'an",
        "第五章 · 西安的改良戏曲"
    ],
    "ch6": [
        "Ch.6 · Politicization and Radicalization",
        "第六章 · 政治化与激进化"
    ],
    "finale": [
        "Finale",
        "终曲"
    ],
    "notes": [
        "Notes",
        "注释"
    ]
}

TITLE_MAP_BODY = {
    "ack": "致谢 · Acknowledgments",
    "overture": "序曲 · Overture",
    "ch1": "第一章 · 回望帝制晚期的戏曲 · Ch.1 · Looking Back at Opera in Late Imperial China",
    "ch2": "第二章 · 中国戏剧话语的变迁 · Ch.2 · Changing Discourses on China's Drama",
    "ch3": "第三章 · 上海京剧的改良 · Ch.3 · The Reformation of Beijing Opera in Shanghai",
    "ch4": "第四章 · 上海舞台上的改良戏曲 · Ch.4 · Reformed Opera on the Shanghai Stage",
    "ch5": "第五章 · 西安的改良戏曲 · Ch.5 · Reformed Opera in Xi'an",
    "ch6": "第六章 · 政治化与激进化 · Ch.6 · Politicization and Radicalization",
    "finale": "终曲 · Finale",
    "notes": "注释 · Notes"
}

SECTITLE_BODY = {
    "ack": "致谢",
    "overture": "序曲",
    "ch1": "第一章 · 回望帝制晚期的戏曲",
    "ch2": "第二章 · 中国戏剧话语的变迁",
    "ch3": "第三章 · 上海京剧的改良",
    "ch4": "第四章 · 上海舞台上的改良戏曲",
    "ch5": "第五章 · 西安的改良戏曲",
    "ch6": "第六章 · 政治化与激进化",
    "finale": "终曲",
    "notes": "注释"
}