#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""TEMPLATE: extract.py — generated by new_book.py. OFFSET 由 part 文件名推断。"""
import glob, json, os
from collections import Counter
import re

HERE = os.path.dirname(os.path.abspath(__file__))

def norm(s):
    return ' '.join(s.split())

def part_rank(folder):
    """按 part 编号给目录排序。support part1 / part1_p1-200 等。"""
    m = re.search(r'part(\d+)', folder)
    return int(m.group(1)) if m else 999


def compute_offset():
    """从 unzip/ 各 part 的 content_list 页数推断每部分起始页偏移。
    第一份 offset=0；后续 = 前面所有份的实际页数（max page_idx+1）累计。"""
    ud = os.path.join(HERE, 'unzip')
    dirs = sorted([d for d in os.listdir(ud) if os.path.isdir(os.path.join(ud, d))],
                  key=part_rank)
    o = {}
    prev_end = 0
    for d in dirs:
        files = glob.glob(os.path.join(ud, d, '*_content_list.json'))
        if not files:
            continue
        data = json.load(open(files[0], encoding='utf-8'))
        npages = max((e['page_idx'] for e in data), default=-1) + 1
        o[d] = prev_end
        prev_end += npages
    return o

def main():
    OFFSET = compute_offset()
    items = []
    for part, off in OFFSET.items():
        files = glob.glob(f'unzip/{part}/*_content_list.json')
        if not files:
            print(f'!! no content_list for {part}'); continue
        d = json.load(open(files[0], encoding='utf-8'))
        for e in d:
            t = norm(e.get('text', ''))
            typ = e.get('type', '')
            if typ in ('footer', 'page_number', 'header', 'image'):
                continue
            if not t:
                continue
            page_start = e['page_idx'] + off + 1
            items.append({'page': page_start, 'type': typ, 'text': t,
                          'lvl': e.get('text_level') if 'text_level' in e else None})
    items.sort(key=lambda x: x['page'])
    with open(os.path.join(HERE, 'stream_raw.json'), 'w', encoding='utf-8') as f:
        json.dump(items, f, ensure_ascii=False)
    print('OFFSET:', OFFSET)
    print('total items:', len(items))
    print('types:', dict(Counter(x['type'] for x in items)))
    print('total chars:', sum(len(x['text']) for x in items))

if __name__ == '__main__':
    main()